// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: invoicer.proto

package invoicer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InvoiceCreate_Create_FullMethodName = "/InvoiceCreate/Create"
)

// InvoiceCreateClient is the client API for InvoiceCreate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvoiceCreateClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type invoiceCreateClient struct {
	cc grpc.ClientConnInterface
}

func NewInvoiceCreateClient(cc grpc.ClientConnInterface) InvoiceCreateClient {
	return &invoiceCreateClient{cc}
}

func (c *invoiceCreateClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, InvoiceCreate_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvoiceCreateServer is the server API for InvoiceCreate service.
// All implementations must embed UnimplementedInvoiceCreateServer
// for forward compatibility
type InvoiceCreateServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedInvoiceCreateServer()
}

// UnimplementedInvoiceCreateServer must be embedded to have forward compatible implementations.
type UnimplementedInvoiceCreateServer struct {
}

func (UnimplementedInvoiceCreateServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedInvoiceCreateServer) mustEmbedUnimplementedInvoiceCreateServer() {}

// UnsafeInvoiceCreateServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvoiceCreateServer will
// result in compilation errors.
type UnsafeInvoiceCreateServer interface {
	mustEmbedUnimplementedInvoiceCreateServer()
}

func RegisterInvoiceCreateServer(s grpc.ServiceRegistrar, srv InvoiceCreateServer) {
	s.RegisterService(&InvoiceCreate_ServiceDesc, srv)
}

func _InvoiceCreate_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceCreateServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceCreate_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceCreateServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvoiceCreate_ServiceDesc is the grpc.ServiceDesc for InvoiceCreate service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvoiceCreate_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "InvoiceCreate",
	HandlerType: (*InvoiceCreateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _InvoiceCreate_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoicer.proto",
}
